export const FETCHING_CAR_DETAILS = "FETCHING_CAR_DETAILS";
export const FETCH_CAR_DETAILS = "FETCH_CAR_DETAILS";
// CAR DETAIL

export const FETCHING_CAR_TASK = "FETCHING_CAR_TASK";
export const FETCHING_CAR_TASK_DONE = "FETCHING_CAR_TASK_DONE";
export const FETCH_CAR_TASK = "FETCH_CAR_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
// TASK
