export const FETCHING_CAR_DETAILS = "FETCHING_CAR_DETAILS";
export const FETCHING_CAR_DETAILS_DONE = "FETCHING_CAR_DETAILS_DONE";
export const FETCH_CAR_DETAILS = "FETCH_CAR_DETAILS";
export const UPDATE_CAR_DETAILS = "UPDATE_CAR_DETAILS";
export const NO_CAR_FOUND = "NO_CAR_FOUND";
// CAR DETAIL
export const FETCH_MAKE = "FETCH_MAKE";

export const FETCH_MODELS = "FETCH_MODELS";
export const FETCH_TRIM = "FETCH_TRIM";
export const CLEAR_ALL = "CLEAR_ALL";
export const CLEAR_TRIM = "CLEAR_TRIM";

export const FETCHING_CAR_INFO = "FETCHING_CAR_INFO";
export const FETCHING_CAR_INFO_DONE = "FETCHING_CAR_INFO_DONE";
// CAR INFO

export const FETCHING_CAR_TASK = "FETCHING_CAR_TASK";
export const FETCHING_CAR_TASK_DONE = "FETCHING_CAR_TASK_DONE";
export const FETCH_CAR_TASK = "FETCH_CAR_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
// TASK
